name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Neovim ${{ matrix.neovim }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        neovim:
          - stable
          - nightly

    steps:
      - name: Checkout citeref
        uses: actions/checkout@v4

      # ── Install Neovim ────────────────────────────────────────────────────
      - name: Install Neovim (${{ matrix.neovim }})
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      # ── Clone plenary.nvim ────────────────────────────────────────────────
      # We install into the packpath location that minimal_init.lua expects.
      - name: Install plenary.nvim
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/test/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            ~/.local/share/nvim/site/pack/test/start/plenary.nvim

      # ── Run tests ─────────────────────────────────────────────────────────
      - name: Run test suite
        run: |
          nvim --headless \
               -u tests/minimal_init.lua \
               -c "PlenaryBustedDirectory tests/ {sequential=true, minimal_init='tests/minimal_init.lua'}" \
               2>&1
          # Plenary exits 0 on success, non-zero on any failure.
          # The 2>&1 ensures we capture output in the Actions log.
